"""Markdown App card renderer."""

from __future__ import annotations

from .models import App, Edge, Warning


def render_card(app: App, edges: list[Edge],
                warnings: list[Warning] | None = None) -> str:
    """Render a Markdown App card for one App."""
    lines: list[str] = []

    lines.append(f"# App: {app.name}")
    lines.append("")

    # Metadata
    lines.append(f"- **Domain**: {app.domain}")
    lines.append(f"- **Path**: `{app.path}`")
    lines.append(f"- **ID**: `{app.id}`")
    if app.signals:
        lines.append(f"- **Signals**: {', '.join(app.signals)}")
    lines.append("")

    # Workloads
    if app.workloads:
        lines.append("## Workloads")
        lines.append("")
        for w in app.workloads:
            replicas_str = f" (×{w.replicas})" if w.replicas is not None else ""
            lines.append(f"- {w.kind}: {w.name}{replicas_str}")
        lines.append("")

    # Services
    if app.services:
        lines.append("## Services")
        lines.append("")
        for svc in app.services:
            ns_str = f" (ns: {svc.namespace})" if svc.namespace else ""
            port_str = f" port={svc.port}" if svc.port else ""
            lines.append(f"- {svc.name}{ns_str}{port_str}")
        lines.append("")

    # Flux objects
    if app.flux_objects:
        lines.append("## Flux Objects")
        lines.append("")
        for fo in app.flux_objects:
            ns_str = f" (ns: {fo.namespace})" if fo.namespace else ""
            lines.append(f"- {fo.kind}: {fo.name}{ns_str}")
        lines.append("")

    # Ingress hosts
    if app.ingress_hosts:
        lines.append("## Ingress Hosts")
        lines.append("")
        for h in app.ingress_hosts:
            lines.append(f"- `{h}`")
        lines.append("")

    # Edges (dependsOn)
    depends_on = [e for e in edges
                  if e.from_app == app.id and e.type == "dependsOn"]
    if depends_on:
        lines.append("## Depends On")
        lines.append("")
        for e in depends_on:
            lines.append(f"- **{e.to_app}** — {e.evidence}")
        lines.append("")

    # Edges (implicit / dns-ref / external-ref)
    implicit = [e for e in edges
                if e.from_app == app.id and e.type in ("dns-ref", "external-ref")]
    if implicit:
        lines.append("## Implicit Dependencies")
        lines.append("")
        for e in implicit:
            lines.append(f"- **{e.to_app}** ({e.type}) — {e.evidence}")
        lines.append("")

    # Referenced by
    referenced_by = [e for e in edges if e.to_app == app.id]
    if referenced_by:
        lines.append("## Referenced By")
        lines.append("")
        for e in referenced_by:
            lines.append(f"- **{e.from_app}** ({e.type}) — {e.evidence}")
        lines.append("")

    # Encrypted flag
    if app.encrypted:
        lines.append("## Encrypted")
        lines.append("")
        lines.append("Contains SOPS-encrypted secrets")
        lines.append("")

    # Warnings for this app
    if warnings:
        app_warnings = [w for w in warnings if w.app == app.id]
        if app_warnings:
            lines.append("## Warnings")
            lines.append("")
            for w in app_warnings:
                lines.append(f"- [{w.kind}] {w.detail}")
            lines.append("")

    lines.append("---")
    lines.append("*Generated by flux-topology*")
    lines.append("")

    return "\n".join(lines)
